### ISSUE TITLE
Create a 'bad actor' scoring system

### ISSUE THREAD

**Issue by Leo552** [openheritage/open-plaques-diversity#11]

**Comment by Leo552** [comment]
![Bad actor score](https://user-images.githubusercontent.com/56204370/85614539-e4c65c80-b652-11ea-9bd2-b9ead6daf1a8.png)

Initial crude scoring system based off words found in the corresponding wiki pages

**Comment by Leo552** [comment]
7 out of the 9 know people with links to slave trading are within the top 100 with this scoring system

**Comment by Leo552** [comment]
Top few names from the combined scoring system:
Robert Milligan
William Ewart Gladstone
Simón Bolívar
Ira Aldridge
Joseph Conrad
Anna Laetitia Barbauld
John Marshall
Quintin Hogg
Elizabeth Barrett Browning
John Adams
Richard Cobden
William Murray, 1st Earl of Mansfield
Benjamin Franklin
Mahatma Gandhi
Charles Darwin
Rt Hon. Lord Henry Brougham PC FRS QC
Major General Charles George Gordon
John Stuart Mill
King William IV of the United Kingdom
Josephine Butler
Sir Francis Drake
William Pitt
James Boswell
William Penn
Dido Elizabeth Belle
G. A. Henty
George Canning
Sir Henry Morton Stanley GCB
Frederick Delius CH
Admiral Robert Fitzroy RN

**Comment by jnicho02** [comment]
This list is getting interesting.

It also gives us a practical process of reviewing the list and going on to OpenPlaques to flag the obvious BAME subjects (Ira Aldridge, Mahatma Gandhi...i've updated them) so that on a re-run they are not included....is this cheating? or is it practical? This is a real-world problem, so I believe that manual intervention is allowed.

Some on the list are authors/poets/composers and have written things with the word 'slave' in the title, prompting their inclusion. Again, it shows the real-world nature of the problem. You could carry on improving the algorithm until it is 'perfect' but maybe you'll overtrain it and miss people out. The purpose is to narrow down a list of suggestions so that we don't have to manually review every single person.

**Comment by Leo552** [comment]
Trying a re-run with actors/poets/... as words which will reduce the bad actor score. This is playing on the correlation that most actor/poets/... were against slavery - will this mean that some are missed?

**Comment by Leo552** [comment]
Altered scoring system results:
Robert Milligan
William Ewart Gladstone
Simón Bolívar
Quintin Hogg
Richard Cobden
William Murray, 1st Earl of Mansfield
Sir Francis Drake
John Marshall
William Penn
Josephine Butler
George Canning
John Adams
Sir Fisher Tench 1st Baronet
Jeremy Bentham
William Pitt
Charles Spurgeon
José de San Martín
Samuel Morse
Mary Seacole

**Comment by Leo552** [comment]
Top few for all of the UK plaques:
Robert Milligan
William Ewart Gladstone
Admiral Sir Edward Codrington RN GCB FRS
Simón Bolívar
John Gladstone FRSE
Quintin Hogg
George Whitefield
Richard Cobden
Dr James Wilson
William Murray, 1st Earl of Mansfield
John Graves Simcoe
Thomas Drayton
Sir Lt Gen Thomas Picton GCB
Sir Francis Drake
John Hancock
...
